---
- name: Setup PXE Server
  hosts: pxeserver
  become: yes

  tasks:
  - name: Stop ufw service
    systemd:
      name: ufw
      state: stopped

  - name: Disable ufw service
    systemd:
      name: ufw
      enabled: no

  - name: Update package list
    apt:
       update_cache: yes

  - name: Install dnsmasq
    apt:
     name: dnsmasq
     state: present

  - name: copy config file
    template:
        src: pxe.conf
        dest: /etc/dnsmasq.d/pxe.conf
        mode: 0640

  - name: Create directory /srv/tftp
    file:
        path: /srv/tftp
        state: directory
        mode: 0755

  - name: Download the Ubuntu 24.04 netboot image
    get_url:
        url: https://cdimage.ubuntu.com/ubuntu-server/noble/daily-live/current/noble-netboot-amd64.tar.gz
        dest: /tmp/noble-netboot-amd64.tar.gz

  - name: Extract the tar file to /srv/tftp
    shell: tar -xzvf /tmp/noble-netboot-amd64.tar.gz -C /srv/tftp
    args:
        creates: /srv/tftp/amd64

  - name: Restart dnsmasq service
    systemd:
        name: dnsmasq
        state: restarted