---
- name: Manage backup machine 1st step
  hosts: backup
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install borgbackup
      apt:
        name: borgbackup
        state: present

    - name: Ensure borg group exists
      group:
        name: borg
        state: present

    - name: Ensure borg user  exist
      user:
        name: borg
        group: borg
        createhome: no

    - name: Create /var/backup directory
      file:
        path: /var/backup
        state: directory
        owner: borg
        group: borg
        mode: '0755'
    
    - name: Create .ssh directory for borg user
      file:
        path: /home/borg/.ssh
        state: directory
        owner: borg
        group: borg
        mode: '0700'

    - name: Create .ssh/authorized_keys file for borg user
      file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg
        mode: '0600'

- name: Manage client machine 1st step
  hosts: client
  become: true
  
  tasks:
      - name: Update package list
        apt:
          update_cache: yes

      - name: Install borgbackup
        apt:
          name: borgbackup
          state: present

      - name: Generate SSH key
        shell: |
         ssh-keygen -t ed25519 -f /home/vagrant/.ssh/id_ed25519 -N ''
      
      - name: Change ownership of /home/vagrant/.ssh
        file:
          path: /home/vagrant/.ssh
          owner: vagrant
          group: vagrant
          recurse: yes

- name: Copy SSH public key from client to backup
  hosts: backup
  become: true
  vars:
    borg_user: borg
    client_public_key_path: "/home/vagrant/.ssh/id_ed25519.pub"

  tasks:
    - name: Fetch the public key from the client
      fetch:
        src: "{{ client_public_key_path }}"
        dest: "/tmp/client_id_ed25519.pub"
        flat: yes
      delegate_to: client

    - name: Add SSH public key to authorized_keys on backup
      authorized_key:
        user: "{{ borg_user }}"
        key: "{{ lookup('file', '/tmp/client_id_ed25519.pub') }}"
        state: present

- name: Manage client machine
  hosts: client
  become: true
  vars:
    borg_passphrase: "Otus1234"

  tasks:
    - name: Initialize Borg repository
      shell: |
        echo "{{ borg_passphrase }}" | borg init --encryption=repokey --passphrase-fd 0 borg@192.168.56.160:/var/backup/
