---
- name: Manage backup machine
  hosts: backup
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install borgbackup
      apt:
        name: borgbackup
        state: present

    - name: Ensure borg group exists
      group:
        name: borg
        state: present

    - name: Ensure borg user  exist
      user:
        name: borg
        group: borg
        createhome: no

    - name: Create /var/backup directory
      file:
        path: /var/backup
        state: directory
        owner: borg
        group: borg
        mode: '0755'

    - name: Create .ssh directory for borg user
      file:
        path: /home/borg/.ssh
        state: directory
        owner: borg
        group: borg
        mode: '0700'

    - name: Create .ssh/authorized_keys file for borg user
      file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg
        mode: '0600'