---
- name: Manage client machine
  hosts: client
  become: true

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install borgbackup
      apt:
        name: borgbackup
        state: present

    - name: Generate SSH key
      shell: |
         ssh-keygen -t ed25519 -f /home/vagrant/id_ed25519 -N ''