Vagrant.configure("2") do |config|
# Base VM OS config
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  #Define 2 VMs with static private IP addresses
  boxes = [
    { :name => "backup",
      :ip => "192.168.56.160",
    },
    { :name => "client",
      :ip => "192.168.56.150",
    }
  ]
  # Provision each of the VMs
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end
  end
end