---
- name: Setup bond interface
  hosts: inetRouter,centralRouter 
  become: yes 
  tasks: 
  - name: set up ifcfg-bond0 
    template: 
      src: ifcfg-bond0.j2 
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0 
      owner: root 
      group: root 
      mode: 0644 
   
  - name: set up en4s,ens5 
    copy:  
      src: "{{ item }}"  
      dest: /etc/sysconfig/network-scripts/ 
      owner: root 
      group: root 
      mode: 0644 
    with_items: 
      - bonding/ifcfg-ens4 
      - bonding/ifcfg-ens5 

  - name: restart hosts for bond0 
    reboot: 
      reboot_timeout: 3600